### ISSUE TITLE
Mod needs a 1.18.2 update

### ISSUE THREAD

**Issue by Sunconure11** [Aureljz/WhenDungeonsArise--Fabric#4]
https://pastebin.com/a6QDDwQT

**Comment by WillowMist** [comment]
Would love to see a 1.18.2 update as well.

**Comment by darksapra** [comment]
Same

**Comment by TheEssem** [comment]
Seems to be somewhat non-trivial due to the removal of the Fabric Structure API in 1.18.2 versions: https://github.com/FabricMC/fabric/commit/420242637b3c2df7341e974561e015100b8d5f8f

The new method is to use datapacks; however, this would mean that the config system would have to be reworked. Mo' Structures worked around this by removing the config file altogether and replacing it with a guide on how to edit the datapack (see `/src/main/java/io/github/frqnny/mostructures/config/MoStructuresConfig.java`): frqnny/mostructures@398bd8fea64dbe77d0027c1fbaf83c909ac1b76a

**Comment by Aureljz** [comment]
The forge version has already been ported to 1.18.2. Fabric may take a bit longer.

Config file will be removed, as the mod will be mainly datapack driven from now on.

**Comment by Ricenami** [comment]
I'm excited for the 1.18.2 FABRIC port!
